param_server:
  ros__parameters:
    name:
      # publish
      grid: "/rmcs_map/map/grid"
      cost: "/rmcs_map/map/cost"
      status: "/rmcs_map/status"
      transformed_map: "/rmcs_map/transformed_map"
      lidar: "/livox/lidar"
      # other
      node: "rmcs_map"
      frame:
        map: "map_link"
        lidar: "lidar_link"
    # process config
    switch:
      # livox | pointcloud2
      pointcloud_type: "livox"
      cost_map: false
      grid_map: true
      publish_transformed_cloud: true
      publish_test: false
    lidar:
      livox_frames: 2
    grid:
      resolution: 0.1
      grid_width: 10.0
      lidar_blind: 1.2
      height_wight: 120.0
      ground_height: 0.2
    filter:
      threshold: 50
      pre_dilate_size: 3
      pre_dilate_times: 2
      pre_close_size: 2
      pre_close_times: 2
      gradient: true
      dilate_size: 2
